CUDA_VISIBLE_DEVICES=1 python ./deduction_model/train.py \
-dn hyper_graph_diginetica \
-m lsgt \
--train_query_dir ./sampled_hyper_train_diginetica_merged_graph_dgl \
--valid_query_dir ./sampled_hyper_valid_dininetica_graph_dgl \
--test_query_dir ./sampled_hyper_test_diginetica_graph_dgl \
--checkpoint_path ./logs \
--num_layers 2 \
-fol  \
-b 1024 \
--log_steps 120000 \
-lr 0.001
